spring.application.name=VtooProject
spring.datasource.url=jdbc:mysql://localhost:3306/vtoo_db
spring.datasource.username=root
spring.datasource.password=komal123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true